local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
#  host: "http://localhost:3001"

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>


#from Rails guide
#amazon:
#  service: S3
#  access_key_id: ""
#  secret_access_key: ""
#  bucket: ""
#  region: "" # e.g. 'us-east-1'